


.PHONY: all
all:
	@echo "nothing to make or download for this example, use 'make run' to run the examples."

.PHONY: run
run:
	@echo "\nmaking run";
	python3 hello_ncs.py;

.PHONY: help
help:
	@echo "possible make targets: ";
	@echo "  make help - shows this message";
	@echo "  make all - makes the following: run";
	@echo "  make run - runs the hello_ncs_cpp executable example program";
	@echo "  make clean - removes all created content and temporary files";

.PHONY: clean
clean:
	@echo "clean done.";
