FROM ubuntu:16.04

# Install necessary packages for the installer
RUN apt-get update && apt-get install -y \
    lsb-release \
    build-essential \
    sed \
    sudo \
    tar \
    udev \
    wget \
    libusb-1.0-0-dev \
    && apt-get clean

# Copy over the NCSDK
COPY ./ ncsdk/

# Set the current working directory to the cloned ncsdk directory
WORKDIR "/ncsdk"

# Run the installer
RUN make install
WORKDIR "api/src"
RUN sudo make clean && sudo make get_mvcmd && sudo make basicinstall NO_BOOT=yes NO_RESET=yes && sudo make pythoninstall
WORKDIR "../../"
